// <auto-generated />
using System;
using GBCSporting_Huskies1.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GBCSporting_Huskies1.Migrations
{
    [DbContext(typeof(CustomerContext))]
    [Migration("20220217074748_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GBCSporting_Huskies1.Models.Catergory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "China"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Canada"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Russia"
                        },
                        new
                        {
                            CategoryId = 4,
                            Name = "United States"
                        },
                        new
                        {
                            CategoryId = 5,
                            Name = "United Kingdom"
                        },
                        new
                        {
                            CategoryId = 6,
                            Name = "Zimbabwe"
                        });
                });

            modelBuilder.Entity("GBCSporting_Huskies1.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("CatergoryCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Postalcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerId");

                    b.HasIndex("CatergoryCategoryId");

                    b.ToTable("Customer");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            Address = "553 Emerson Drive",
                            CategoryId = 1,
                            City = "Gotham",
                            DateAdded = new DateTime(2022, 2, 17, 2, 47, 48, 157, DateTimeKind.Local).AddTicks(6357),
                            Email = "something@yahoo.com",
                            Firstname = "Pepe",
                            Lastname = "The Clown",
                            Phone = "5567921312",
                            Postalcode = "T6R 3F7",
                            State = "Washington"
                        });
                });

            modelBuilder.Entity("GBCSporting_Huskies1.Models.Customer", b =>
                {
                    b.HasOne("GBCSporting_Huskies1.Models.Catergory", "Catergory")
                        .WithMany()
                        .HasForeignKey("CatergoryCategoryId");

                    b.Navigation("Catergory");
                });
#pragma warning restore 612, 618
        }
    }
}
